<a href="https://colab.research.google.com/github/mrpahadi2609/Data_Structure/blob/main/NUMPY_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

THEORITICAL QUESTIONS

In [ ]:
## QUES 1)  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
## enhance Python's capabilities for numerical operations?

NumPy, which stands for Numerical Python, is a powerful library in Python that is widely used for scientific computing and data analysis. Here are some key purposes and advantages of using NumPy:

 * Purpose of NumPy:
1. Efficient Array Operations: NumPy provides a high-performance multidimensional array object called ndarray, which allows for efficient storage and manipulation of large datasets.
2. Numerical Computing: It is designed for numerical computing, making it easier to perform mathematical operations on large arrays and matrices.
3. Integration with Other Libraries: NumPy serves as the foundational library for many other scientific libraries in Python, such as SciPy, Pandas, and Matplotlib, enhancing their capabilities.

   * Advantages of NumPy:
1. Performance: NumPy's array operations are implemented in C, making them significantly faster compared to traditional Python lists. This speed is crucial for handling large datasets and performing complex calculations.
2. Convenient Syntax: NumPy provides a user-friendly syntax for mathematical operations, allowing for concise and readable code. For example, you can perform element-wise operations directly on arrays without the need for loops.
3. Broadcasting: This feature allows NumPy to perform operations on arrays of different shapes, making it easier to work with datasets of varying dimensions.
4. Comprehensive Mathematical Functions: NumPy includes a wide range of mathematical functions, such as trigonometric, statistical, and algebraic functions, which can be applied to arrays.
5. Memory Efficiency: NumPy arrays consume less memory than Python lists, which is essential when working with large datasets.
6. Support for Linear Algebra: NumPy includes functions for linear algebra operations, such as matrix multiplication, eigenvalue decomposition, and more, which are fundamental in scientific computing.

* Enhancing Python's Capabilities:
NumPy enhances Python's capabilities for numerical operations by providing a robust framework for handling large datasets efficiently. It allows users to perform complex mathematical computations with ease and speed, which would be cumbersome and slow using standard Python data structures. Additionally, its interoperability with other libraries means that it forms the backbone of the scientific Python ecosystem, enabling advanced data analysis and visualization.

In summary, NumPy is essential for anyone involved in scientific computing or data analysis with Python due to its efficiency, performance, and extensive functionality. It transforms Python into a powerful tool for numerical operations, making it a go-to choice for researchers and data scientists alike.

In [ ]:
## QUES 2) Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
## other?

The np.mean() and np.average() functions in NumPy are both used to calculate averages, but they have some differences in their functionality and use cases. Here’s a comparison of the two:

### np.mean()
- Purpose: Calculates the arithmetic mean of the elements in an array.
- Basic Usage: You simply pass the array (or list) to the function, and it computes the mean.
- Syntax: np.mean(a, axis=None, dtype=None, out=None)
- Parameters:
  - a: Input array.
  - axis: Axis along which the means are computed. Default is None, meaning the mean is computed over the entire array.
  - dtype: Data type to use in computing the mean.
  - out: Alternative output array to store the result.
- Behavior: It does not take weights into account; it treats all elements equally.

### np.average()
- Purpose: Calculates the weighted average of the elements in an array.
- Basic Usage: You can pass an array and optionally specify weights for the elements.
- Syntax: np.average(a, axis=None, weights=None, returned=False)
- Parameters:
  - a: Input array.
  - axis: Axis along which the averages are computed.
  - weights: An optional array of the same shape as a, specifying the weights for each element.
  - returned: If set to True, it also returns the sum of the weights.
- Behavior: It allows for weighting the contributions of different elements, which can be useful in various contexts.

### When to Use Each:
- Use np.mean() when you need a simple arithmetic mean of the data without any weights. It’s straightforward and efficient for general purposes.
- Use np.average() when you need to compute a weighted average. This is particularly useful in scenarios where certain data points should contribute more to the average than others, such as in statistical analysis or when dealing with datasets where some values are more significant than others.

### Example:
If you have an array of exam scores and you want to find the average score, you would use np.mean(). However, if you have scores along with their respective weights (like credit hours for courses), you would use np.average() to get a more accurate representation of the overall performance.

In summary, while both functions serve to compute averages, np.mean() is for straightforward calculations, and np.average() is for when you need to account for the importance of different values through weights.

In [ ]:
## QUES 3)  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
## arrays.

Reversing a NumPy array can be done along different axes using various methods. Here are the methods for both 1D and 2D arrays.

* Reversing a 1D Array
For a 1D array, you can reverse the array using slicing. The syntax for slicing is array[::-1], which means you take the entire array but step backwards.

Example:
python
import numpy as np

* Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

* Reverse the 1D array
reversed_array_1d = array_1d[::-1]

print(reversed_array_1d)  # Output: [5 4 3 2 1]


* Reversing a 2D Array
For a 2D array, you can reverse the array along a specific axis using slicing as well. You can reverse along the first axis (rows) or the second axis (columns).

1. Reversing along the first axis (rows):
   This reverses the order of the rows in the array.

   Example:
   python
   import numpy as np

   * Create a 2D array
   array_2d = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

   # Reverse the 2D array along the first axis (rows)
   reversed_array_2d_rows = array_2d[::-1]

   print(reversed_array_2d_rows)
   # Output:
   # [[7 8 9]
   #  [4 5 6]
   #  [1 2 3]]
   

2. Reversing along the second axis (columns):
   This reverses the order of the columns in the array.

   Example:
   python
   import numpy as np

   8 Create a 2D array
   array_2d = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

   * Reverse the 2D array along the second axis (columns)
   reversed_array_2d_columns = array_2d[:, ::-1]

   print(reversed_array_2d_columns)
   # Output:
   # [[3 2 1]
   #  [6 5 4]
   #  [9 8 7]]
   

* Summary
- For a 1D array, use array[::-1] to reverse the array.
- For a 2D array, you can reverse along the first axis with array[::-1] and along the second axis with array[:, ::-1].

These methods provide a straightforward way to reverse arrays in NumPy, whether they are one-dimensional or two-dimensional.

In [ ]:
## QUES 4)  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
## in memory management and performance.

To determine the data type of elements in a NumPy array, you can use the dtype attribute of the array. This attribute returns the data type of the array elements, which is crucial for understanding how the array will behave in terms of memory usage and performance.

### Example of Determining Data Type
Here's a simple example to illustrate how to find the data type of a NumPy array:

python
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Get the data type of the array elements
data_type = array.dtype

print(data_type)  # Output: int64 (or int32 depending on the system)


### Importance of Data Types
1. Memory Management: Different data types consume different amounts of memory. For example, an int64 type uses 8 bytes per element, while an int32 uses only 4 bytes. By choosing the appropriate data type for your array, you can significantly reduce memory usage, especially for large datasets.

2. Performance: The choice of data type can also affect performance. Operations on smaller data types (like float32 instead of float64) can be faster because they require less computational power and memory bandwidth. This can lead to quicker calculations, especially in numerical computations or when working with large arrays.

3. Precision: Different data types offer different ranges and precision. For example, float32 can represent a smaller range of decimal values than float64. Choosing the right data type ensures that your calculations maintain the necessary precision without unnecessary overhead.

4. Compatibility: Certain functions and operations in NumPy may require specific data types. Understanding the data types helps in avoiding errors and ensuring compatibility when performing operations or combining arrays.

In summary, knowing the data type of elements in a NumPy array is essential for efficient memory management, optimizing performance, maintaining precision, and ensuring compatibility with various operations.

In [ ]:
## QUES 5) Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, ndarrays (short for "n-dimensional arrays") are a powerful data structure used to store and manipulate large datasets. They are the core feature of the NumPy library and provide a wide range of functionalities for numerical computations.

### Key Features of ndarrays:
1. Homogeneous Data: All elements in an ndarray must be of the same data type, which allows for optimized memory usage and performance. This is in contrast to Python lists, which can hold elements of different types.

2. Multidimensional: Ndarrays can have any number of dimensions (hence "n-dimensional"). You can create 1D arrays (vectors), 2D arrays (matrices), and even higher-dimensional arrays. This flexibility is crucial for scientific computing and data analysis.

3. Efficient Memory Usage: Ndarrays are more memory-efficient than Python lists. They store data in contiguous blocks of memory, which reduces overhead and improves cache performance.

4. Vectorized Operations: NumPy allows for element-wise operations on ndarrays without the need for explicit loops. This leads to cleaner code and significantly faster execution times, as operations are implemented in optimized C code.

5. Broadcasting: Ndarrays support broadcasting, a powerful mechanism that allows for arithmetic operations between arrays of different shapes. This means you can perform operations on arrays of different sizes without needing to manually adjust their shapes.

6. Indexing and Slicing: Ndarrays provide advanced indexing and slicing capabilities, allowing you to easily access and manipulate subsets of data.

### Differences from Standard Python Lists:
- Data Type: Python lists can hold mixed data types, while ndarrays require all elements to be of the same type.
- Performance: Ndarrays are generally faster and more efficient for numerical operations compared to Python lists, especially for large datasets.
- Functionality: Ndarrays come with a rich set of built-in mathematical functions and operations that are not available with standard lists. For example, you can easily perform linear algebra operations, statistical calculations, and more with ndarrays.
- Memory Layout: Ndarrays are stored in a contiguous block of memory, while Python lists are arrays of pointers to objects, leading to more overhead.

In summary, ndarrays are a fundamental part of NumPy that enable efficient and powerful numerical computations, offering advantages in terms of performance, memory usage, and functionality compared to standard Python lists.

In [ ]:
## QUES 6)  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

When it comes to large-scale numerical operations, NumPy arrays provide several performance benefits over standard Python lists. Here’s a detailed analysis:

### 1. Speed:
   - Vectorization: NumPy allows for vectorized operations, meaning that operations can be applied to entire arrays at once without the need for explicit loops. This leads to significant performance improvements since NumPy uses optimized C and Fortran libraries under the hood.
   - Compiled Code: NumPy functions are implemented in compiled languages, which run much faster than Python’s interpreted code. This means that operations on NumPy arrays are generally executed much quicker than equivalent operations on Python lists.

### 2. Memory Efficiency:
   - Contiguous Memory Allocation: NumPy arrays store data in contiguous blocks of memory, which reduces the overhead associated with Python lists (which store references to objects). This layout not only saves space but also improves cache performance when accessing elements.
   - Fixed Data Types: Since all elements in a NumPy array are of the same data type, NumPy can use a more compact representation of the data, reducing memory overhead compared to lists that can store mixed types.

### 3. Reduced Overhead:
   - Lower Memory Overhead: Python lists have a higher memory overhead due to their ability to store heterogeneous data types. NumPy arrays, being homogeneous, eliminate this overhead, allowing for more efficient use of memory.
   - Less Python Object Overhead: Each element in a Python list is a reference to a Python object, which adds additional overhead. In contrast, NumPy arrays store data in a more streamlined manner.

### 4. Advanced Mathematical Operations:
   - Built-in Functions: NumPy provides a wide range of built-in mathematical functions that are optimized for performance. These functions can operate on entire arrays at once, which is not possible with Python lists without writing custom loops.
   - Broadcasting: NumPy’s broadcasting feature allows for operations between arrays of different shapes without needing to manually adjust their dimensions. This capability simplifies code and enhances performance.

### 5. Parallel Processing:
   - Optimized Libraries: Many NumPy operations leverage optimized libraries like BLAS and LAPACK, which can take advantage of multi-core processors for parallel computations. This can lead to further performance gains for large-scale numerical operations.

### Conclusion:
In summary, when performing large-scale numerical operations, NumPy arrays significantly outperform Python lists in terms of speed, memory efficiency, and functionality. The ability to leverage vectorized operations and optimized libraries makes NumPy the preferred choice for numerical computing in Python. If you’re dealing with large datasets or complex calculations, using NumPy arrays can lead to substantial improvements in performance and efficiency.

In [ ]:
## QUES 7) Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
## output.

The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively. Here’s a comparison of both functions along with examples to demonstrate their usage and output.

### vstack()
The vstack() function stacks arrays in sequence vertically (row-wise). This means it adds rows to an array.

Example:
python
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

# Stack arrays vertically
result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)


Output:

Result of vstack:
[[1 2]
 [3 4]
 [5 6]]


### hstack()
The hstack() function stacks arrays in sequence horizontally (column-wise). This means it adds columns to an array.

Example:
python
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])

# Stack arrays horizontally
result_hstack = np.hstack((array1, array2))

print("Result of hstack:")
print(result_hstack)


Output:

Result of hstack:
[[1 2 5]
 [3 4 6]]


### Summary
- vstack() combines arrays vertically, adding rows from the second array to the first.
- hstack() combines arrays horizontally, adding columns from the second array to the first.

These functions are particularly useful for combining datasets in various shapes, making NumPy a powerful tool for numerical operations and data manipulation.

In [ ]:
## QUES 8)  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
## array dimensions.

The fliplr() and flipud() methods in NumPy are used to flip arrays along different axes. Here’s a detailed explanation of the differences between these two methods, including their effects on various array dimensions.

### fliplr()
The fliplr() function flips an array left to right. This means it reverses the order of the columns in a 2D array.

Example:
python
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Flip the array left to right
result_fliplr = np.fliplr(array)

print("Result of fliplr:")
print(result_fliplr)


Output:

Result of fliplr:
[[3 2 1]
 [6 5 4]]


### flipud()
The flipud() function flips an array up to down. This means it reverses the order of the rows in a 2D array.

Example:
python
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Flip the array up to down
result_flipud = np.flipud(array)

print("Result of flipud:")
print(result_flipud)


Output:

Result of flipud:
[[4 5 6]
 [1 2 3]]


### Effects on Various Array Dimensions
1. 2D Arrays:
   - fliplr() reverses the columns, while flipud() reverses the rows.
   
2. 1D Arrays:
   - Both functions will have the same effect as they essentially reverse the order of elements in the array.

Example for 1D Array:
python
array_1d = np.array([1, 2, 3, 4])

result_fliplr_1d = np.fliplr(array_1d.reshape(1, -1))  # Reshape to 2D for fliplr
result_flipud_1d = np.flipud(array_1d.reshape(1, -1))  # Reshape to 2D for flipud

print("Result of fliplr on 1D array:")
print(result_fliplr_1d)

print("Result of flipud on 1D array:")
print(result_flipud_1d)


Output:

Result of fliplr on 1D array:
[[4 3 2 1]]
Result of flipud on 1D array:
[[1 2 3 4]]


### Summary
- fliplr() is used to flip arrays left to right (affects columns).
- flipud() is used to flip arrays up to down (affects rows).
- Both functions are primarily used for 2D arrays but can be applied to 1D arrays as well, with the need to reshape them for fliplr().

These functions are very useful for data manipulation and transformation in various applications, including image processing and data analysis.

In [ ]:
## QUES 9) Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into multiple sub-arrays. This method is particularly useful when you want to divide an array into smaller segments for further processing or analysis.

### Functionality of array_split()

1. Basic Usage:
   The array_split() method takes two main arguments: the array you want to split and the number of splits you want to create.

   Syntax:
   python
   numpy.array_split(ary, indices_or_sections, axis=0)
   

   - ary: The input array you want to split.
   - indices_or_sections: This can be an integer (number of equal splits) or a list of indices where the array should be split.
   - axis: The axis along which to split the array. The default is 0, which means it splits along the first axis (rows for 2D arrays).

2. Example:
   Here’s a simple example of how to use array_split():

   python
   import numpy as np

   # Create a 1D array
   array = np.array([1, 2, 3, 4, 5, 6])

   # Split the array into 3 parts
   split_array = np.array_split(array, 3)

   print("Split Array:")
   print(split_array)
   

   Output:
   
   Split Array:
   [array([1, 2]), array([3, 4]), array([5, 6])]
   

### Handling Uneven Splits

When you use array_split() with an integer for the number of sections, it will try to create sub-arrays as evenly as possible. However, if the array cannot be evenly divided, the last sub-array will contain the remaining elements.

For example, if you have an array of 7 elements and you want to split it into 3 parts, the result will be:

python
array = np.array([1, 2, 3, 4, 5, 6, 7])
split_array = np.array_split(array, 3)

print("Split Array with uneven parts:")
print(split_array)


Output:

Split Array with uneven parts:
[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In this case, the first sub-array contains 3 elements while the other two contain 2 elements each.

### Summary

- array_split() is a versatile method for dividing arrays into smaller segments.
- It can handle uneven splits gracefully by distributing the remaining elements into the last sub-array.
- This functionality is particularly useful when dealing with datasets that need batch processing or when you want to analyze parts of an array independently.

Overall, array_split() is a powerful tool for managing and manipulating data in NumPy.

In [ ]:
## QUES 10) Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
## operations?

Vectorization and broadcasting are two fundamental concepts in NumPy that significantly enhance the efficiency of array operations.

### Vectorization

Vectorization refers to the process of converting operations that would typically be performed in a loop into a single operation that can be applied to entire arrays at once. This is possible because NumPy is built on optimized C and Fortran libraries, allowing it to perform operations on entire arrays without the need for explicit loops in Python.

For example, if you want to add two arrays element-wise, you can do it directly without looping through each element:

python
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
result = a + b
print(result)  # Output: [5 7 9]


In this example, the addition is performed in a single operation, making it much faster than using a loop.

### Broadcasting

Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes. When you perform operations between two arrays, NumPy automatically expands the smaller array across the larger one so that they have compatible shapes. This is particularly useful when you want to perform operations between a scalar and an array or between arrays of different dimensions.

For instance, if you have a 1D array and a 2D array, broadcasting allows you to add them together:

python
# A 1D array
a = np.array([1, 2, 3])

# A 2D array
b = np.array([[4, 5, 6],
              [7, 8, 9]])

# Broadcasting addition
result = a + b
print(result)


Output:

[[ 5  7  9]
 [ 8 10 12]]


In this case, the 1D array a is broadcasted to match the shape of the 2D array b, allowing for element-wise addition.

### Contribution to Efficient Array Operations

Both vectorization and broadcasting contribute to efficient array operations in several ways:

1. Performance: By eliminating the need for explicit loops in Python, vectorization speeds up computations. Operations are executed at a lower level in optimized libraries, which is much faster than interpreted Python code.

2. Memory Efficiency: Broadcasting allows for operations on arrays of different shapes without needing to create large temporary arrays, saving memory and improving performance.

3. Cleaner Code: Both concepts lead to more concise and readable code. Instead of writing complex loops, you can express operations in a straightforward manner, making the code easier to understand and maintain.

In summary, vectorization and broadcasting are powerful features of NumPy that enable efficient and fast array operations, making it a preferred choice for numerical computations in Python.

PRACTICAL QUESTIONS

In [1]:
## QUES 1) Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T

# Print the transposed array
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[46 46 49]
 [66 11 21]
 [40 55 35]]

Transposed Array:
[[46 66 40]
 [46 11 55]
 [49 21 35]]


In [2]:
## QUES 2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)

# Print the original 1D array
print("Original 1D Array:")
print(array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
## QUES 3)  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Print the original 4x4 array
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)

Original 4x4 Array:
[[0.42855829 0.61436272 0.45291026 0.00420113]
 [0.4158929  0.96042236 0.44410353 0.15772879]
 [0.914566   0.25729985 0.69351958 0.09280695]
 [0.87453192 0.99376452 0.50570516 0.99351422]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.42855829 0.61436272 0.45291026 0.00420113 0.        ]
 [0.         0.4158929  0.96042236 0.44410353 0.15772879 0.        ]
 [0.         0.914566   0.25729985 0.69351958 0.09280695 0.        ]
 [0.         0.87453192 0.99376452 0.50570516 0.99351422 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
## QUES 4)  Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Print the resulting array
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [5]:
## QUES 5)  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array)
lowercase = np.char.lower(array)
titlecase = np.char.title(array)
capitalize = np.char.capitalize(array)

# Print the original and transformed arrays
print("Original Array:")
print(array)

print("\nUppercase:")
print(uppercase)

print("\nLowercase:")
print(lowercase)

print("\nTitle Case:")
print(titlecase)

print("\nCapitalized:")
print(capitalize)

Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


In [6]:
## QUES 6) Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Print the original and modified arrays
print("Original Array:")
print(words_array)

print("\nArray with Spaces Between Characters:")
print(spaced_words)

Original Array:
['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


In [7]:
## QUES 7)  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

array2 = np.array([[10, 20, 30],
                    [40, 50, 60]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[10 20 30]
 [40 50 60]]

Element-wise Addition:
[[11 22 33]
 [44 55 66]]

Element-wise Subtraction:
[[ -9 -18 -27]
 [-36 -45 -54]]

Element-wise Multiplication:
[[ 10  40  90]
 [160 250 360]]

Element-wise Division:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [8]:
## QUES 8)  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the identity matrix
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the diagonal elements
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [9]:
## QUES 9)  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
# this array.
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Print the random integers and the prime numbers found
print("Random Integers:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Integers:
[350 862 427 605 768 349 573 106 202 390 414 966 695 481 121  41 253 398
 671 203 930 345 605 167 999 949 570 507 226  35 781 329  79 180 424 444
 386 311 840 786 128 900 288 612 368 231 937 638 133 658 359 290 201 201
 123 619 464  66 584 352 640 554 740 477 882  36  90 602 990 138 647 279
 398 872 286 372 434 446 119 666 678 688 797 180  57 928 960  90 736 291
 473 460  39 169  60 770 812 252 377 862]

Prime Numbers in the Array:
[349  41 167  79 311 937 359 619 647 797]


In [10]:
## QUES 10)  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
# averages.
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

# Calculate the weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

# Display the weekly averages
for week, avg in enumerate(weekly_averages, start=1):
    print(f"Week {week} average temperature: {avg:.2f}°C")

Week 1 average temperature: 28.00°C
Week 2 average temperature: 35.00°C
Week 3 average temperature: 42.00°C
Week 4 average temperature: 49.00°C
Week 5 average temperature: 53.50°C
